catppuccin/notepad-plus-plus

README.md

Downloading the files from GitHub can be quicker and more convenient than cloning this whole repository, so we should suggest that instead.

docs(usage): avoid suggesting git cloning repository

---

notepad-plus-plus.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Frappe: 
Macchiato: 
Mocha: 
Latte 🔆 🕶️ 🩸 :
Related to #4

feat: add vhdl and verilog language styles

---

notepad-plus-plus.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

These files are already encoding in utf-8, this just fixes the xml prolog to be consistent, as stated in the docs:
https://npp-user-manual.org/docs/config-files/#configuration-file-encoding

fix: xml prolog encoding to utf-8 for consistency

---

notepad-plus-plus.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

In Notepad++ v8.5 onward, special hidden characters can have a custom theme color.
If users have the options enabled as described in: https://npp-user-manual.org/docs/views/#show-symbol, the characters will be themed appropriately.
Using yellow because I think it looks nice.

feat: theme eol and non-print character style

---

.gitattributes

This will prevent showing diffs in Github PRs by default.
You can click the "show" button to view changes anyway.

chore: mark themes/* as linguist-generated

---

notepad-plus-plus.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Brings consistency with other Catppuccin code editor ports (vscode, nvim, etc)
This is kinda a major endeavor that can't just be me in a day. 
Your preference whether this should be a giant collaborative pr+branch,
Or small changes one lang at a time like this.
Demo of VS Code, Neovim, and (this pr) Npp in that order

feat: update xml lang to match styleguide

---

README.md

Copying this line into the config file will be a lot less annoying than manually entering the RGB values for every element in the settings GUI. It will also automatically select the desired syntax theme. 
Annoyingly, this file can't be edited by Npp itself, because it overwrites any changes when it closes! So that's not ideal...
I actually generated these using a whiskers template, but I wasn't sure how that should be integrated into the repo. So I didn't include it in this commit.
Would like to see if these instructions are clear and work for others.

feat: provide config.xml snippet in readme for ui colors

---

templates/editor.tera
templates/ui.tera
ui-theme.md

For any future travellers, `2.5.1` contains an important fix that ensures the `--check` command works properly with multiple files.

refactor: update whiskers to `2.5.1` & fix indentation

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

There were hard-coded selected text and active line overlay colors that I fixed. This makes selected text and active line consistent across flavors.
I also changed the automatic brace and "smart text" match highlighting to use a common 'selected text' mix (overlay2 30% mix with base).
If there is a better way to do this in whiskers + tera let me know.
Before:
Fixed:

fix: improve selected text and active line highlights

---

.gitattributes

This will allow syntax highlighting for template files on Github.com
It may also affect the language distribution chart for the repository, once the server runs analysis and updates the display.

chore: add linguist-language attribute for tera templates

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Added new groups (recent version v8.7.7) and re-themed a few things with the VSCode port as a role model.
Left npp, right vscode
If there are any changes you'd like to see, hmu. Sadly, @jack-mil found out that a lot of the things vscode let's us theme, npp just can't theme indivually. That unfortunately means that we have to find compromises for some things.

fix: python highlighting to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Added a new (?) hightlight group that was missing from before, "KEY" to style ini table keys

fix: ini config highlighting to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Brings the bash syntax theme up to date with the style-guide.
The lexer is not very advanced, and doesn't support many contexts.
This will not look nearly as good VS Code or Neovim with a proper language server or tree-sitter.
But it's probably the best Npp can do with the built-in language support.
Relates to #17
| Before | After |
| -- | -- |
| ![bash-before](https://github.com/user-attachments/assets/38004b43-06f3-47b9-85d7-985f77e54d23) | ![bash-after](https://github.com/user-attachments/assets/cedf4455-bfd6-4b5b-b6ab-f60d1ac09978) |
For reference, here is VS Code's highlight group capability.

fix: bash highlighting to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Added many groups that are either new or were missing from the old theme.
Unsure what the best way to handle the "ERROR" group is. See screenshots.
Comment highlighting is enabled by setting the editor language to JSON5 instead of the default JSON.
|     |     |
| --: | :-- |
| latte | ![json-after-latte](https://github.com/user-attachments/assets/45c076f5-f4bd-4fd3-90c8-7cfcf4a05e04) |
| frappe | ![json-after-frappe](https://github.com/user-attachments/assets/8bd90730-3714-433f-869d-fe522aba453b) |
| mocha | ![json-after-mocha](https://github.com/user-attachments/assets/d9b1bc7b-04e9-499c-9216-c374d20fac51) |

fix: json highlighting to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Again, the Npp language syntax lexer is very basic, so this results in a much less colorful theme then VSCode (esp. in doc-comments)
| Before | After |
| :-- | :-- |
| ![lua-before](https://github.com/user-attachments/assets/4201eefe-9d20-46f8-a4d9-1978f644bd90) | ![lua-after](https://github.com/user-attachments/assets/43983498-7523-4aa5-8d4e-6e5c2d5eb435) |
| Idea for doc-comments (?) | ![lua-after-docs](https://github.com/user-attachments/assets/6d5c691d-ba71-44fe-b4c8-54dc1aec4b23) | 
| Another example |
| :--: |
| <img src="https://github.com/user-attachments/assets/992b81ea-5ba8-4ed5-a759-1cd73abd5fc5" width=60%> |
| VS Code for reference | 
| :--: |
| <img src="https://github.com/user-attachments/assets/6abf34c3-b478-4f8d-a2b6-42d6d8ea7abd" width=60%>  |
To be merged *after* #14 …

fix: lua highlighting to match styleguide

---

templates/editor.tera
templates/ui.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml
ui-theme.md

Adds all the style groups to match the default (stylers.xml) available in the most recent version of Npp (v8.7.7).
I have also re-ordered the list to match the default style for clarity.
Includes these groups:
- Multi-selected text color (30% overlay2, 70% base)
- Multi-edit carets [cursor] color (rosewater)
- Bookmark margin (base)
- Change History Margin (base)
- Fold Margin (base)
- Incremental highlight all ( Search > Incremental Search [Ctrl+Alt+I] ) (blue)
- Active tab unfoced indicator (I can't identify what this actually changes) 
- Active tab text fg color text
- Inactive tabs (foreground and background) (subtext, crust)
- Document map (view > document map) ( surface2 )
- Orders the keys to match built-in theme (effects order in UI as well)
- Adds a couple missing styles (Find …

feat: add missing and new global style groups

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Including both because they have nearly identical highlight groups
I wish we could highlight functions and classes blue & yellow, but doesn't seem like Npp lexers can detect that.
| Frappe | Latte |
| ------- | ----- |
| ![image](https://github.com/user-attachments/assets/3e1e4c44-c04d-423a-b8be-43cdd36af3fa) | ![image](https://github.com/user-attachments/assets/8e4395ce-09ad-4330-a79e-d22266970975) |
| Frappe | Latte |
| ------- | ----- |
| ![image](https://github.com/user-attachments/assets/b84575fe-aa3a-4253-989b-779a91ea35f7) | ![image](https://github.com/user-attachments/assets/914de4b6-d6cf-45db-ad49-5eb9269b2975) |
<details>
<summary>Before, for reference</summary>
</details>
Relates to #33

fix: java & c# highlighting to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

This example is gibberish, but shows the highlighting
Relates to #17 
<sub><em> god-forsaken language </em></sub>

fix: batch to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Cheating a little by making the IDENTIFIER group yellow. 
Everything that is yellow in this image would be `text` otherwise.
<details>
<summary> Rust was essentially broken before </summary>
</summary>

fix: rust to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

fix: yaml highlighting to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Also adds many new highlight groups from recent NotePad++ versions. The previous Typescript just straight up didn't work in the current notepad++ version (probably because the `styleId`s have changed.
There are two (2) supported "javascript" languages, one for a `*.js` file, and the other for embedded javascript in html `<script>` tags. They have slightly different highlight group names, but I made the syntax colors the same. 
| Javascript | Typescript |
| :----------: | :---------: |
| ![image](https://github.com/user-attachments/assets/5ea826d8-edc8-4dc2-ae0a-cf2e15840001) | ![image](https://github.com/user-attachments/assets/49cd8b66-29a8-4013-a178-181a7dcc762f) |
I would not recommend doing any serious web development in NotePad++ :joy:
<details>
<summary> Old version (javascript) …

fix: javascript and typescript to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

| Before | After |
| ------ | ----- |
| ![before](https://github.com/user-attachments/assets/945af75b-4291-4a9e-a978-0f127250e110) | ![after](https://github.com/user-attachments/assets/c1e4f6a1-9504-439c-be3c-4d0125251429) |
Everything that you see text colored is part of the "VALUE" group, and is all styled as one unfortunately. 
Relates to #17

fix: css to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Here is a weird one, and the most advanced and feature complete support from Npp yet!
I am actually strangely familiar with Motorolla S-Records because of some previous projects, so this was nice to see.
| Macciato | Latte |
| ---------- | ------ |
| ![image](https://github.com/user-attachments/assets/4f1a370c-1693-4f08-9ee6-a4d66d4006c1) | ![image](https://github.com/user-attachments/assets/29907c19-c3d3-4343-8f32-dc41b8a283a1) |
Everything can be statically analyzed, so i'm guessing that's why there is so much support for validation from the syntax theme.
Why there is built-in support for a "binary" program format from the '70s, I have no idea. 
See: https://en.wikipedia.org/wiki/SREC_(file_format)
Relates to #33

feat: add S-record highlighting

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Finally something that might actually offer a slight improvement over the VS Code default!
| Notepad++ | VS Code |
| ------------- | --------- |
| ![image](https://github.com/user-attachments/assets/fd961217-06e1-4120-82ae-f195ec95a84d) | ![image](https://github.com/user-attachments/assets/32d5570c-8488-4160-adb3-54b4e1ef33d1) |
The choices of color are a bit arbitrary, but I personally think it looks nice.
Relates to #33

feat: add git diff syntax highlighting

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Also includes fixes that I missed for XML. HTML and XML should be more consistent with each-other now
I can't seem to change the fg color of the actual !DOCTYPE header text. It's not affected by any of the styles as I can see, not even DEFAULT.

fix: html (& xml) to match styleguide

---

README.md

- Clarify install instructions, particularily in regard to modifying the default typeface/font.
- Remove obsolete Dracula reference.
- Add myself to the maintainer list.

docs: instructions for changing font name/size

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

| Frappe | Latte |
| :-----: | :-----: |
| ![Screenshot 2025-04-10 142257](https://github.com/user-attachments/assets/ff900096-aef7-4b62-9185-f2d160869008) | ![Screenshot 2025-04-10 142317](https://github.com/user-attachments/assets/b01d3a29-684c-434d-83ea-8d757b884c0d) |

fix: matlab to match styleguide

---

.github/workflows/check.yml
templates/editor.tera
templates/ui.tera

We can't fully use the reusable workflow yet but at least we can stop hard-coding the version now :+1:

ci(check): update setup-whiskers

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

This is a special docked window that opens when using "Find all in Current Document". For some reason it is configured like a language style.

fix: search result window styling

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Includes the addition of a couple missing (new) styles
Examples:

fix: SQL to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

I don't know, it's some wacky freeware Windows automation thing. 
~~Probably the sort of thing N++ users would use all the time.~~
Kinda insane how these obscure languages have better highlighting support than the c/c++ family. Guess that's where the interest is.
<sub>samples from [wikipedia ](https://en.wikipedia.org/wiki/AutoIt) and a random forum post</sub>

fix: autoit to match style guide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Dead language, but will include it in case some poor soul has to edit pascal code in N++ on some ancient system.

fix: pascal to match style guide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

I do not know why they don't have a style for keywords. Default theme also does not style `import/if/endif/else` etc.

fix: makefile to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Unother weird obscure Windows automation scripting language
Exactly the sort of thing people recommend N++ for.

fix: kixtart to match style guide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Not sure _exactly_ why these are two seperate language definitions with completely different highlight groups, but whatever. 
I tried to match them as best I could.
| Latte | Macchiato| 
| ------ | ---------- |
| ![image](https://github.com/user-attachments/assets/951f0c67-9b75-420a-8dc5-7c485e886464) | ![image](https://github.com/user-attachments/assets/2e9f2394-384c-4ce3-950a-7714083015b1) |
| Latte | Mocha |
| ------ | ------- |
| ![image](https://github.com/user-attachments/assets/e247cd6f-ac71-41cd-a361-0dbc23409155) | ![image](https://github.com/user-attachments/assets/9f3f362c-a22c-4eb0-8310-a26920b29c4f) |
Relates to #33

feat: add TeX and update LaTeX languages

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

|  |   |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/faeaf36d-6106-457b-b2ff-386ad089870d) | ![image](https://github.com/user-attachments/assets/c9b1f6bc-7cd4-48c0-985c-6390b773d978)

fix: ruby to match styleguide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

Lots of colors available for this one, nice to see. 
Erlang must have been easier for Lexilla to parse and identify

fix: erlang to match style guide

---

templates/editor.tera
themes/catppuccin-frappe.xml
themes/catppuccin-latte.xml
themes/catppuccin-macchiato.xml
themes/catppuccin-mocha.xml

These are the Registry key/values for easy configuration.
Something likely to be edited/views in N++.
Relates to #33

feat: add Windows Registry syntax highlighting
